"""PDF report generation for investigations."""

import io
from datetime import datetime, timezone
from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from src.adapters.db.repositories import SqlAlchemyInvestigationRepository
from src.adapters.db.scan_result_repository import SqlAlchemyScanResultRepository
from src.api.v1.auth.dependencies import get_current_user
from src.core.domain.entities.user import User
from src.dependencies import get_db

router = APIRouter()


def _generate_html_report(investigation, scan_results, identities) -> str:
    """Generate an HTML report that can be converted to PDF."""
    seeds_html = "".join(
        f"<tr><td>{s.input_type.value}</td><td><code>{s.value}</code></td></tr>"
        for s in investigation.seed_inputs
    )

    scans_html = "".join(
        f"<tr><td>{r.scanner_name}</td><td>{r.input_value}</td><td>{r.status.value}</td>"
        f"<td>{len(r.extracted_identifiers)}</td><td>{r.duration_ms}ms</td></tr>"
        for r in scan_results
    )

    findings_html = ""
    for r in scan_results:
        if r.raw_data and not r.raw_data.get("_stub"):
            findings_html += f"<h3>{r.scanner_name} — {r.input_value}</h3>"
            findings_html += "<table>"
            for k, v in r.raw_data.items():
                if k.startswith("_") or k == "extracted_identifiers" or k == "raw_results":
                    continue
                if isinstance(v, list):
                    findings_html += f"<tr><td><strong>{k}</strong></td><td>{', '.join(str(x) for x in v[:10])}</td></tr>"
                elif v:
                    findings_html += f"<tr><td><strong>{k}</strong></td><td>{v}</td></tr>"
            findings_html += "</table>"

    total_findings = sum(len(r.extracted_identifiers) for r in scan_results)
    successful = sum(1 for r in scan_results if r.status.value == "success")

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body {{ font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1d24; padding: 40px; max-width: 800px; margin: 0 auto; }}
    h1 {{ color: #0fb8b5; border-bottom: 2px solid #0fb8b5; padding-bottom: 8px; }}
    h2 {{ color: #333; margin-top: 30px; }}
    h3 {{ color: #555; margin-top: 20px; }}
    table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
    td, th {{ padding: 8px 12px; border: 1px solid #e0e0e0; text-align: left; font-size: 13px; }}
    th {{ background: #f5f5f5; font-weight: 600; }}
    code {{ background: #f0f0f0; padding: 2px 6px; border-radius: 3px; font-size: 12px; }}
    .meta {{ color: #666; font-size: 13px; }}
    .stats {{ display: flex; gap: 20px; margin: 15px 0; }}
    .stat {{ background: #f8f9fa; padding: 12px 20px; border-radius: 8px; text-align: center; }}
    .stat-value {{ font-size: 24px; font-weight: 700; color: #0fb8b5; }}
    .stat-label {{ font-size: 11px; color: #888; text-transform: uppercase; }}
    .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #e0e0e0; color: #999; font-size: 11px; }}
</style>
</head>
<body>
<h1>OSINT Investigation Report</h1>
<p class="meta"><strong>{investigation.title}</strong></p>
<p class="meta">{investigation.description}</p>
<p class="meta">Status: {investigation.status.value} | Created: {investigation.created_at.strftime('%Y-%m-%d %H:%M UTC')}</p>

<div class="stats">
    <div class="stat"><div class="stat-value">{len(scan_results)}</div><div class="stat-label">Scans</div></div>
    <div class="stat"><div class="stat-value">{successful}</div><div class="stat-label">Successful</div></div>
    <div class="stat"><div class="stat-value">{total_findings}</div><div class="stat-label">Findings</div></div>
</div>

<h2>Seed Inputs</h2>
<table><tr><th>Type</th><th>Value</th></tr>{seeds_html}</table>

<h2>Scan Results</h2>
<table><tr><th>Scanner</th><th>Input</th><th>Status</th><th>Findings</th><th>Duration</th></tr>{scans_html}</table>

<h2>Detailed Findings</h2>
{findings_html if findings_html else "<p>No detailed findings available.</p>"}

<div class="footer">
    Generated by OSINT Platform on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}<br>
    This report is confidential and intended only for authorized recipients.
</div>
</body>
</html>"""


@router.get("/{investigation_id}/report")
async def generate_pdf_report(
    investigation_id: UUID,
    current_user: Annotated[User, Depends(get_current_user)],
    db: Annotated[AsyncSession, Depends(get_db)],
) -> StreamingResponse:
    """Generate a PDF report for an investigation."""
    inv_repo = SqlAlchemyInvestigationRepository(db)
    investigation = await inv_repo.get_by_id(investigation_id)
    if investigation is None or investigation.owner_id != current_user.id:
        raise HTTPException(status_code=404, detail="Investigation not found")

    scan_repo = SqlAlchemyScanResultRepository(db)
    scan_results = await scan_repo.get_by_investigation(investigation_id)

    html = _generate_html_report(investigation, scan_results, [])

    # Try WeasyPrint for PDF, fall back to HTML
    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html).write_pdf()
        return StreamingResponse(
            io.BytesIO(pdf_bytes),
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="report-{investigation_id}.pdf"'},
        )
    except ImportError:
        # Fallback: return HTML report
        return StreamingResponse(
            io.BytesIO(html.encode()),
            media_type="text/html",
            headers={"Content-Disposition": f'attachment; filename="report-{investigation_id}.html"'},
        )
