"""Repository port for payment orders."""

from typing import Protocol
from uuid import UUID

from src.core.domain.entities.payment import PaymentOrder, PaymentWebhookLog


class IPaymentOrderRepository(Protocol):
    async def save(self, order: PaymentOrder) -> PaymentOrder: ...
    async def get_by_id(self, order_id: UUID) -> PaymentOrder | None: ...
    async def get_by_external_id(self, external_id: str) -> PaymentOrder | None: ...
    async def get_by_user(self, user_id: UUID) -> list[PaymentOrder]: ...
    async def is_processed(self, external_payment_id: str) -> bool: ...


class IPaymentWebhookLogRepository(Protocol):
    async def save(self, log: PaymentWebhookLog) -> PaymentWebhookLog: ...
