from typing import Protocol
from uuid import UUID

from src.core.domain.entities.identity import Identity
from src.core.domain.entities.investigation import Investigation
from src.core.domain.entities.user import User
from src.core.domain.entities.graph_node import GraphNode
from src.core.domain.entities.graph_edge import GraphEdge
from src.core.domain.value_objects.email import Email


class IUserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: Email) -> User | None: ...
    async def save(self, user: User) -> User: ...
    async def delete(self, user_id: UUID) -> None: ...


class IInvestigationRepository(Protocol):
    async def get_by_id(self, investigation_id: UUID) -> Investigation | None: ...
    async def list_by_owner(self, owner_id: UUID, page: int = 1, size: int = 20) -> tuple[list[Investigation], int]: ...
    async def save(self, investigation: Investigation) -> Investigation: ...
    async def delete(self, investigation_id: UUID) -> None: ...


class IIdentityRepository(Protocol):
    async def get_by_id(self, identity_id: UUID) -> Identity | None: ...
    async def get_by_investigation(self, investigation_id: UUID) -> list[Identity]: ...
    async def find_similar(self, identity: Identity, threshold: float = 0.7) -> list[Identity]: ...
    async def save(self, identity: Identity) -> Identity: ...
    async def bulk_save(self, identities: list[Identity]) -> list[Identity]: ...


class IGraphRepository(Protocol):
    async def add_node(self, node: GraphNode) -> GraphNode: ...
    async def add_edge(self, edge: GraphEdge) -> GraphEdge: ...
    async def get_subgraph(self, investigation_id: UUID, depth: int = 2) -> tuple[list[GraphNode], list[GraphEdge]]: ...
    async def find_paths(self, source_id: UUID, target_id: UUID, max_depth: int = 5) -> list[list[GraphNode]]: ...
