#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${1:-.env}"

if [ -f "$ENV_FILE" ]; then
    echo "WARNING: $ENV_FILE already exists. Backing up to ${ENV_FILE}.bak"
    cp "$ENV_FILE" "${ENV_FILE}.bak"
fi

cat > "$ENV_FILE" << EOF
# Generated by generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
APP_ENV=production
DEBUG=false

SECRET_KEY=$(openssl rand -hex 32)
JWT_SECRET_KEY=$(openssl rand -hex 32)

POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=osint
POSTGRES_USER=osint
POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=')

REDIS_URL=redis://redis:6379/0

NEO4J_URI=bolt://neo4j:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=')

MINIO_ENDPOINT=minio:9000
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=$(openssl rand -base64 24 | tr -d '/+=')
MINIO_BUCKET=osint-data

NOWPAYMENTS_API_KEY=
NOWPAYMENTS_IPN_SECRET=$(openssl rand -hex 32)
NOWPAYMENTS_SANDBOX=true

BASE_URL=http://localhost:8080
FRONTEND_URL=http://localhost:8080

CORS_ORIGINS=["http://localhost:8080"]

OSINT_SCAN_TIMEOUT_SECONDS=120
OSINT_MAX_CONCURRENT_SCANS=5
OSINT_DEFAULT_SCAN_DEPTH=2

RATE_LIMIT_REQUESTS=100
RATE_LIMIT_WINDOW_SECONDS=60

GRAFANA_PASSWORD=$(openssl rand -base64 16 | tr -d '/+=')
FLOWER_USER=admin
FLOWER_PASSWORD=$(openssl rand -base64 16 | tr -d '/+=')
EOF

echo "Secrets generated in $ENV_FILE"
echo "IMPORTANT: Keep this file secure and never commit it to version control."
