"""Platform registry for username presence detection.

Curated database of platforms with not-found indicators and category metadata.
Designed for multi-factor confidence scoring — HTTP status alone is insufficient
for many platforms that return 200 even for missing profiles.
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class PlatformEntry:
    """Metadata for a single platform in the username presence registry."""

    name: str
    url_template: str  # Must contain {username}
    category: str  # social | developer | gaming | creative | professional | forum | finance
    # Strings that appear in the response body of a *missing* profile page
    not_found_indicators: tuple[str, ...] = field(default_factory=tuple)
    # Strings that confirm a *real* profile page
    found_indicators: tuple[str, ...] = field(default_factory=tuple)
    # How reliable HTTP 200 is for this platform (1.0 = perfect, 0.5 = unreliable)
    confidence_weight: float = 0.8
    # Whether this platform requires a GET (not HEAD) to read content
    requires_body: bool = True


PLATFORM_REGISTRY: dict[str, PlatformEntry] = {
    # ── Social / General ───────────────────────────────────────────────────────
    "GitHub": PlatformEntry(
        name="GitHub",
        url_template="https://github.com/{username}",
        category="developer",
        not_found_indicators=("Not Found", "This is not the web page you are looking for"),
        found_indicators=("repositories", "followers", "following"),
        confidence_weight=0.95,
    ),
    "Twitter": PlatformEntry(
        name="Twitter",
        url_template="https://twitter.com/{username}",
        category="social",
        not_found_indicators=("This account doesn\u2019t exist", "Hmm...this page doesn\u2019t exist"),
        found_indicators=(),
        confidence_weight=0.75,
    ),
    "Reddit": PlatformEntry(
        name="Reddit",
        url_template="https://www.reddit.com/user/{username}",
        category="forum",
        not_found_indicators=("Sorry, nobody on Reddit goes by that name", "page not found"),
        found_indicators=("karma", "cake day"),
        confidence_weight=0.95,
    ),
    "Instagram": PlatformEntry(
        name="Instagram",
        url_template="https://www.instagram.com/{username}/",
        category="social",
        not_found_indicators=("Sorry, this page isn\u2019t available"),
        found_indicators=(),
        confidence_weight=0.8,
    ),
    "TikTok": PlatformEntry(
        name="TikTok",
        url_template="https://www.tiktok.com/@{username}",
        category="social",
        not_found_indicators=("Couldn\u2019t find this account"),
        found_indicators=(),
        confidence_weight=0.7,
    ),
    "YouTube": PlatformEntry(
        name="YouTube",
        url_template="https://www.youtube.com/@{username}",
        category="social",
        not_found_indicators=("This page isn\u2019t available"),
        found_indicators=("subscribers",),
        confidence_weight=0.8,
    ),
    "Pinterest": PlatformEntry(
        name="Pinterest",
        url_template="https://www.pinterest.com/{username}/",
        category="creative",
        not_found_indicators=("Hmm\u2026 that page doesn\u2019t exist"),
        found_indicators=("Pins", "Followers"),
        confidence_weight=0.85,
    ),
    "Tumblr": PlatformEntry(
        name="Tumblr",
        url_template="https://{username}.tumblr.com/",
        category="social",
        not_found_indicators=("There\u2019s nothing here.", "404"),
        found_indicators=(),
        confidence_weight=0.75,
    ),
    "Medium": PlatformEntry(
        name="Medium",
        url_template="https://medium.com/@{username}",
        category="professional",
        not_found_indicators=("Page not found"),
        found_indicators=("followers", "Following"),
        confidence_weight=0.85,
    ),
    "Snapchat": PlatformEntry(
        name="Snapchat",
        url_template="https://www.snapchat.com/add/{username}",
        category="social",
        not_found_indicators=(),
        found_indicators=("Add me on Snapchat",),
        confidence_weight=0.9,
    ),
    # ── Developer Platforms ────────────────────────────────────────────────────
    "GitLab": PlatformEntry(
        name="GitLab",
        url_template="https://gitlab.com/{username}",
        category="developer",
        not_found_indicators=("The page you\u2019re looking for could not be found"),
        found_indicators=("Overview", "Activity", "Groups"),
        confidence_weight=0.9,
    ),
    "Bitbucket": PlatformEntry(
        name="Bitbucket",
        url_template="https://bitbucket.org/{username}/",
        category="developer",
        not_found_indicators=("Sorry, we can\u2019t find that page"),
        found_indicators=(),
        confidence_weight=0.85,
    ),
    "Keybase": PlatformEntry(
        name="Keybase",
        url_template="https://keybase.io/{username}",
        category="developer",
        not_found_indicators=("Not a Keybase user"),
        found_indicators=("Keybase proof", "on keybase"),
        confidence_weight=0.95,
    ),
    "HackerNews": PlatformEntry(
        name="HackerNews",
        url_template="https://news.ycombinator.com/user?id={username}",
        category="forum",
        not_found_indicators=("No such user."),
        found_indicators=("karma",),
        confidence_weight=0.98,
    ),
    "StackOverflow": PlatformEntry(
        name="StackOverflow",
        url_template="https://stackoverflow.com/users/{username}",
        category="developer",
        not_found_indicators=("Page Not Found"),
        found_indicators=("reputation", "badges"),
        confidence_weight=0.7,  # URL uses numeric IDs, username may be slug
    ),
    "Dev.to": PlatformEntry(
        name="Dev.to",
        url_template="https://dev.to/{username}",
        category="developer",
        not_found_indicators=("404", "Route not found"),
        found_indicators=("posts", "comments"),
        confidence_weight=0.9,
    ),
    "Replit": PlatformEntry(
        name="Replit",
        url_template="https://replit.com/@{username}",
        category="developer",
        not_found_indicators=("Page not found"),
        found_indicators=("Repls", "followers"),
        confidence_weight=0.9,
    ),
    "Codepen": PlatformEntry(
        name="Codepen",
        url_template="https://codepen.io/{username}",
        category="developer",
        not_found_indicators=("The pen you are looking for could not be found", "Hmm"),
        found_indicators=("Pens", "followers"),
        confidence_weight=0.85,
    ),
    "npm": PlatformEntry(
        name="npm",
        url_template="https://www.npmjs.com/~{username}",
        category="developer",
        not_found_indicators=("Not found", "User not found"),
        found_indicators=("packages",),
        confidence_weight=0.9,
    ),
    "PyPI": PlatformEntry(
        name="PyPI",
        url_template="https://pypi.org/user/{username}/",
        category="developer",
        not_found_indicators=("404", "Not Found"),
        found_indicators=("projects",),
        confidence_weight=0.95,
    ),
    "DockerHub": PlatformEntry(
        name="DockerHub",
        url_template="https://hub.docker.com/u/{username}/",
        category="developer",
        not_found_indicators=("404", "Page not found"),
        found_indicators=("repositories",),
        confidence_weight=0.9,
    ),
    "HackerRank": PlatformEntry(
        name="HackerRank",
        url_template="https://www.hackerrank.com/{username}",
        category="developer",
        not_found_indicators=("Uh oh! Something went wrong", "page not found"),
        found_indicators=("Badges", "Certificates"),
        confidence_weight=0.85,
    ),
    "LeetCode": PlatformEntry(
        name="LeetCode",
        url_template="https://leetcode.com/{username}/",
        category="developer",
        not_found_indicators=("does not exist"),
        found_indicators=("problems solved", "contest rating"),
        confidence_weight=0.9,
    ),
    "Kaggle": PlatformEntry(
        name="Kaggle",
        url_template="https://www.kaggle.com/{username}",
        category="developer",
        not_found_indicators=("404", "We could not find"),
        found_indicators=("competitions", "notebooks"),
        confidence_weight=0.85,
    ),
    # ── Creative Platforms ─────────────────────────────────────────────────────
    "Behance": PlatformEntry(
        name="Behance",
        url_template="https://www.behance.net/{username}",
        category="creative",
        not_found_indicators=("This URL doesn\u2019t exist", "Page Not Found"),
        found_indicators=("Projects", "Appreciations"),
        confidence_weight=0.9,
    ),
    "Dribbble": PlatformEntry(
        name="Dribbble",
        url_template="https://dribbble.com/{username}",
        category="creative",
        not_found_indicators=("Whoops, that page is gone", "404"),
        found_indicators=("shots", "followers"),
        confidence_weight=0.9,
    ),
    "Flickr": PlatformEntry(
        name="Flickr",
        url_template="https://www.flickr.com/people/{username}/",
        category="creative",
        not_found_indicators=("Oops! We can't find that page"),
        found_indicators=("photos", "albums"),
        confidence_weight=0.85,
    ),
    "Vimeo": PlatformEntry(
        name="Vimeo",
        url_template="https://vimeo.com/{username}",
        category="creative",
        not_found_indicators=("Sorry, we couldn\u2019t find that page"),
        found_indicators=("videos", "followers"),
        confidence_weight=0.85,
    ),
    "SoundCloud": PlatformEntry(
        name="SoundCloud",
        url_template="https://soundcloud.com/{username}",
        category="creative",
        not_found_indicators=("We can\u2019t find that user", "404"),
        found_indicators=("followers", "tracks"),
        confidence_weight=0.9,
    ),
    # ── Gaming Platforms ───────────────────────────────────────────────────────
    "Steam": PlatformEntry(
        name="Steam",
        url_template="https://steamcommunity.com/id/{username}",
        category="gaming",
        not_found_indicators=("The specified profile could not be found", "Error"),
        found_indicators=("Steam Level",),
        confidence_weight=0.9,
    ),
    "Twitch": PlatformEntry(
        name="Twitch",
        url_template="https://www.twitch.tv/{username}",
        category="gaming",
        not_found_indicators=("Sorry. Unless you\u2019ve got a time machine",),
        found_indicators=("followers",),
        confidence_weight=0.85,
    ),
    "Chess.com": PlatformEntry(
        name="Chess.com",
        url_template="https://www.chess.com/member/{username}",
        category="gaming",
        not_found_indicators=("Oops! That page doesn\u2019t exist",),
        found_indicators=("Games", "Rating"),
        confidence_weight=0.95,
    ),
    # ── Professional Platforms ─────────────────────────────────────────────────
    "ProductHunt": PlatformEntry(
        name="ProductHunt",
        url_template="https://www.producthunt.com/@{username}",
        category="professional",
        not_found_indicators=("Page not found",),
        found_indicators=("followers", "upvotes"),
        confidence_weight=0.85,
    ),
    "AngelList": PlatformEntry(
        name="AngelList",
        url_template="https://angel.co/{username}",
        category="professional",
        not_found_indicators=("Page not found", "404"),
        found_indicators=(),
        confidence_weight=0.75,
    ),
    "About.me": PlatformEntry(
        name="About.me",
        url_template="https://about.me/{username}",
        category="professional",
        not_found_indicators=("The page you are looking for doesn\u2019t exist", "404"),
        found_indicators=(),
        confidence_weight=0.9,
    ),
    # ── Forums / Communities ───────────────────────────────────────────────────
    "Quora": PlatformEntry(
        name="Quora",
        url_template="https://www.quora.com/profile/{username}",
        category="forum",
        not_found_indicators=("This page may have been removed",),
        found_indicators=("answers", "followers"),
        confidence_weight=0.8,
    ),
    "Goodreads": PlatformEntry(
        name="Goodreads",
        url_template="https://www.goodreads.com/{username}",
        category="forum",
        not_found_indicators=("Page not found",),
        found_indicators=("books", "friends"),
        confidence_weight=0.8,
    ),
    "Mastodon": PlatformEntry(
        name="Mastodon",
        url_template="https://mastodon.social/@{username}",
        category="social",
        not_found_indicators=("The page you are looking for isn\u2019t here",),
        found_indicators=("followers", "following"),
        confidence_weight=0.85,
    ),
    # ── Music Platforms ────────────────────────────────────────────────────────
    "Last.fm": PlatformEntry(
        name="Last.fm",
        url_template="https://www.last.fm/user/{username}",
        category="creative",
        not_found_indicators=("User not found",),
        found_indicators=("scrobbles", "Loved Tracks"),
        confidence_weight=0.95,
    ),
    "Spotify": PlatformEntry(
        name="Spotify",
        url_template="https://open.spotify.com/user/{username}",
        category="creative",
        not_found_indicators=("Page not found",),
        found_indicators=(),
        confidence_weight=0.7,
    ),
    # ── Misc ───────────────────────────────────────────────────────────────────
    "Pastebin": PlatformEntry(
        name="Pastebin",
        url_template="https://pastebin.com/u/{username}",
        category="misc",
        not_found_indicators=("Not Found (#404)",),
        found_indicators=("Public Pastes",),
        confidence_weight=0.9,
    ),
    "Gravatar": PlatformEntry(
        name="Gravatar",
        url_template="https://en.gravatar.com/{username}",
        category="misc",
        not_found_indicators=("Not Found",),
        found_indicators=("Profile",),
        confidence_weight=0.9,
    ),
    "Duolingo": PlatformEntry(
        name="Duolingo",
        url_template="https://www.duolingo.com/profile/{username}",
        category="misc",
        not_found_indicators=("We cannot find this user",),
        found_indicators=("streak", "XP"),
        confidence_weight=0.9,
    ),
    "Strava": PlatformEntry(
        name="Strava",
        url_template="https://www.strava.com/athletes/{username}",
        category="misc",
        not_found_indicators=("Oops!", "athlete could not be found"),
        found_indicators=("Activities", "followers"),
        confidence_weight=0.7,  # Uses numeric IDs
    ),
    "Telegram": PlatformEntry(
        name="Telegram",
        url_template="https://t.me/{username}",
        category="social",
        not_found_indicators=(),
        found_indicators=("If you have Telegram",),
        confidence_weight=0.85,
    ),
    "Codecademy": PlatformEntry(
        name="Codecademy",
        url_template="https://www.codecademy.com/profiles/{username}",
        category="developer",
        not_found_indicators=("404",),
        found_indicators=("courses", "streak"),
        confidence_weight=0.85,
    ),
    # ── Competitive Programming ────────────────────────────────────────────────
    "CodeChef": PlatformEntry(
        name="CodeChef",
        url_template="https://www.codechef.com/users/{username}",
        category="developer",
        not_found_indicators=("Sorry, the page you are looking for", "404"),
        found_indicators=("Rating", "Problems Solved", "Global Rank"),
        confidence_weight=0.90,
    ),
    "CodeWars": PlatformEntry(
        name="CodeWars",
        url_template="https://www.codewars.com/users/{username}",
        category="developer",
        not_found_indicators=("is not a member of Codewars", "404"),
        found_indicators=("Honor", "Clan", "Languages"),
        confidence_weight=0.92,
    ),
    "Codeforces": PlatformEntry(
        name="Codeforces",
        url_template="https://codeforces.com/profile/{username}",
        category="developer",
        not_found_indicators=("User with handle", "not found"),
        found_indicators=("Codeforces Round", "rating", "contribution"),
        confidence_weight=0.90,
    ),
    "AtCoder": PlatformEntry(
        name="AtCoder",
        url_template="https://atcoder.jp/users/{username}",
        category="developer",
        not_found_indicators=("404", "No such user"),
        found_indicators=("Rating", "Highest Rating"),
        confidence_weight=0.90,
    ),
    "TopCoder": PlatformEntry(
        name="TopCoder",
        url_template="https://www.topcoder.com/members/{username}",
        category="developer",
        not_found_indicators=("404", "Page not found"),
        found_indicators=("Rating", "Challenges"),
        confidence_weight=0.80,
    ),
    # ── Gaming ─────────────────────────────────────────────────────────────────
    "Osu": PlatformEntry(
        name="Osu",
        url_template="https://osu.ppy.sh/users/{username}",
        category="gaming",
        not_found_indicators=("User not found!", "404"),
        found_indicators=("Performance", "Ranked Score", "Play Count"),
        confidence_weight=0.92,
    ),
    "Roblox": PlatformEntry(
        name="Roblox",
        url_template="https://www.roblox.com/user.aspx?username={username}",
        category="gaming",
        not_found_indicators=("Page cannot be found", "404"),
        found_indicators=("Friends", "Followers"),
        confidence_weight=0.80,
    ),
    "Xbox": PlatformEntry(
        name="Xbox",
        url_template="https://www.xboxgamertag.com/search/{username}",
        category="gaming",
        not_found_indicators=("Gamertag not found", "404"),
        found_indicators=("Gamerscore", "Achievements"),
        confidence_weight=0.75,
    ),
    "PSN": PlatformEntry(
        name="PSN",
        url_template="https://psnprofiles.com/{username}",
        category="gaming",
        not_found_indicators=("User Not Found", "404"),
        found_indicators=("Trophies", "Games Played"),
        confidence_weight=0.85,
    ),
    "Itch.io": PlatformEntry(
        name="Itch.io",
        url_template="https://{username}.itch.io/",
        category="gaming",
        not_found_indicators=("404", "is not a valid"),
        found_indicators=("games", "Browse"),
        confidence_weight=0.85,
    ),
    "Minecraft": PlatformEntry(
        name="Minecraft",
        url_template="https://namemc.com/profile/{username}",
        category="gaming",
        not_found_indicators=("Not Found", "No such player"),
        found_indicators=("Skin", "Cape", "UUID"),
        confidence_weight=0.88,
    ),
    # ── Social / International ─────────────────────────────────────────────────
    "VK": PlatformEntry(
        name="VK",
        url_template="https://vk.com/{username}",
        category="social",
        not_found_indicators=("This page no longer exists", "404"),
        found_indicators=("friends", "followers", "wall"),
        confidence_weight=0.85,
    ),
    "OK": PlatformEntry(
        name="OK",
        url_template="https://ok.ru/{username}",
        category="social",
        not_found_indicators=("Page not found", "404"),
        found_indicators=("friends", "photos", "videos"),
        confidence_weight=0.78,
    ),
    "Minds": PlatformEntry(
        name="Minds",
        url_template="https://www.minds.com/{username}",
        category="social",
        not_found_indicators=("Page not found",),
        found_indicators=("subscribers", "views"),
        confidence_weight=0.82,
    ),
    "Gab": PlatformEntry(
        name="Gab",
        url_template="https://gab.com/{username}",
        category="social",
        not_found_indicators=("Profile not found", "404"),
        found_indicators=("followers", "following", "posts"),
        confidence_weight=0.82,
    ),
    "Parler": PlatformEntry(
        name="Parler",
        url_template="https://parler.com/{username}",
        category="social",
        not_found_indicators=("404", "not found"),
        found_indicators=("followers", "echo"),
        confidence_weight=0.70,
    ),
    "Mewe": PlatformEntry(
        name="Mewe",
        url_template="https://mewe.com/i/{username}",
        category="social",
        not_found_indicators=("404",),
        found_indicators=("followers", "profile"),
        confidence_weight=0.70,
    ),
    # ── Fediverse / Decentralized ──────────────────────────────────────────────
    "Lemmy": PlatformEntry(
        name="Lemmy",
        url_template="https://lemmy.world/u/{username}",
        category="forum",
        not_found_indicators=("Couldn't find that username", "404"),
        found_indicators=("Posts", "Comments", "Joined"),
        confidence_weight=0.85,
    ),
    "Pixelfed": PlatformEntry(
        name="Pixelfed",
        url_template="https://pixelfed.social/@{username}",
        category="creative",
        not_found_indicators=("Sorry, that page doesn't exist", "404"),
        found_indicators=("followers", "photos"),
        confidence_weight=0.82,
    ),
    "Peertube": PlatformEntry(
        name="Peertube",
        url_template="https://tube.tchncs.de/accounts/{username}",
        category="creative",
        not_found_indicators=("404",),
        found_indicators=("videos", "subscribers"),
        confidence_weight=0.72,
    ),
    # ── Creative / Content ─────────────────────────────────────────────────────
    "Wattpad": PlatformEntry(
        name="Wattpad",
        url_template="https://www.wattpad.com/user/{username}",
        category="creative",
        not_found_indicators=("Hmm, we couldn't find that", "404"),
        found_indicators=("reads", "followers", "stories"),
        confidence_weight=0.88,
    ),
    "AO3": PlatformEntry(
        name="AO3",
        url_template="https://archiveofourown.org/users/{username}",
        category="creative",
        not_found_indicators=("Sorry! We couldn't find", "404"),
        found_indicators=("Works", "Bookmarks", "Collections"),
        confidence_weight=0.90,
    ),
    "Bandcamp": PlatformEntry(
        name="Bandcamp",
        url_template="https://bandcamp.com/{username}",
        category="creative",
        not_found_indicators=("404", "We can't find"),
        found_indicators=("albums", "fans"),
        confidence_weight=0.82,
    ),
    "Reverbnation": PlatformEntry(
        name="Reverbnation",
        url_template="https://www.reverbnation.com/{username}",
        category="creative",
        not_found_indicators=("Page Not Found", "404"),
        found_indicators=("fans", "songs", "shows"),
        confidence_weight=0.80,
    ),
    "Letterboxd": PlatformEntry(
        name="Letterboxd",
        url_template="https://letterboxd.com/{username}/",
        category="creative",
        not_found_indicators=("Sorry, we can't find the page", "404"),
        found_indicators=("Films", "Following", "Watchlist"),
        confidence_weight=0.90,
    ),
    "Trakt": PlatformEntry(
        name="Trakt",
        url_template="https://trakt.tv/users/{username}",
        category="creative",
        not_found_indicators=("404", "Page not found"),
        found_indicators=("movies watched", "episodes watched"),
        confidence_weight=0.88,
    ),
    "Myspace": PlatformEntry(
        name="Myspace",
        url_template="https://myspace.com/{username}",
        category="social",
        not_found_indicators=("404", "Page not found"),
        found_indicators=("Songs", "Mixes", "Photos"),
        confidence_weight=0.65,
    ),
    # ── Professional / Freelance ───────────────────────────────────────────────
    "Fiverr": PlatformEntry(
        name="Fiverr",
        url_template="https://www.fiverr.com/{username}",
        category="professional",
        not_found_indicators=("Oops! Something went wrong", "404"),
        found_indicators=("Reviews", "Orders in Queue", "Gigs"),
        confidence_weight=0.88,
    ),
    "Upwork": PlatformEntry(
        name="Upwork",
        url_template="https://www.upwork.com/freelancers/~{username}",
        category="professional",
        not_found_indicators=("404", "Page not found"),
        found_indicators=("Job Success", "Total Earnings"),
        confidence_weight=0.70,
    ),
    "Freelancer": PlatformEntry(
        name="Freelancer",
        url_template="https://www.freelancer.com/u/{username}",
        category="professional",
        not_found_indicators=("Page Not Found", "404"),
        found_indicators=("Reviews", "Skills", "Portfolio"),
        confidence_weight=0.80,
    ),
    "Crunchbase": PlatformEntry(
        name="Crunchbase",
        url_template="https://www.crunchbase.com/person/{username}",
        category="professional",
        not_found_indicators=("404", "Oops, looks like something went wrong"),
        found_indicators=("Founded", "Investments", "Advisory Roles"),
        confidence_weight=0.75,
    ),
    "IndieHackers": PlatformEntry(
        name="IndieHackers",
        url_template="https://www.indiehackers.com/{username}",
        category="professional",
        not_found_indicators=("404", "Page not found"),
        found_indicators=("Followers", "Posts", "Products"),
        confidence_weight=0.85,
    ),
    # ── Academic / Research ────────────────────────────────────────────────────
    "Academia": PlatformEntry(
        name="Academia",
        url_template="https://independent.academia.edu/{username}",
        category="professional",
        not_found_indicators=("Page not found", "404"),
        found_indicators=("Papers", "Citations", "Views"),
        confidence_weight=0.80,
    ),
    "ResearchGate": PlatformEntry(
        name="ResearchGate",
        url_template="https://www.researchgate.net/profile/{username}",
        category="professional",
        not_found_indicators=("404", "Page not found"),
        found_indicators=("Publications", "Citations", "Research Interest Score"),
        confidence_weight=0.80,
    ),
    # ── Security / Hacking Communities ────────────────────────────────────────
    "HackerOne": PlatformEntry(
        name="HackerOne",
        url_template="https://hackerone.com/{username}",
        category="developer",
        not_found_indicators=("404", "Oops! This isn't a page"),
        found_indicators=("Reputation", "Signal", "Impact"),
        confidence_weight=0.90,
    ),
    "Bugcrowd": PlatformEntry(
        name="Bugcrowd",
        url_template="https://bugcrowd.com/{username}",
        category="developer",
        not_found_indicators=("404", "Page Not Found"),
        found_indicators=("Hall of Fame", "points"),
        confidence_weight=0.85,
    ),
    "XDA": PlatformEntry(
        name="XDA",
        url_template="https://forum.xda-developers.com/m/{username}/",
        category="developer",
        not_found_indicators=("The member", "does not exist", "404"),
        found_indicators=("Posts", "Likes", "Joined"),
        confidence_weight=0.85,
    ),
    # ── Art / Design ───────────────────────────────────────────────────────────
    "DeviantArt": PlatformEntry(
        name="DeviantArt",
        url_template="https://www.deviantart.com/{username}",
        category="creative",
        not_found_indicators=("Page Not Found", "404"),
        found_indicators=("Deviations", "Watchers", "Gallery"),
        confidence_weight=0.88,
    ),
    "ArtStation": PlatformEntry(
        name="ArtStation",
        url_template="https://www.artstation.com/{username}",
        category="creative",
        not_found_indicators=("404", "Page not found"),
        found_indicators=("Projects", "Followers", "Likes"),
        confidence_weight=0.88,
    ),
    "Furaffinity": PlatformEntry(
        name="Furaffinity",
        url_template="https://www.furaffinity.net/user/{username}/",
        category="creative",
        not_found_indicators=("This user cannot be found", "404"),
        found_indicators=("Watchers", "Submissions"),
        confidence_weight=0.85,
    ),
    # ── Blogging / Writing ─────────────────────────────────────────────────────
    "Substack": PlatformEntry(
        name="Substack",
        url_template="https://{username}.substack.com",
        category="professional",
        not_found_indicators=("404", "Oops! This page doesn't exist"),
        found_indicators=("Subscribe", "Subscribers", "Posts"),
        confidence_weight=0.82,
    ),
    "Ghost": PlatformEntry(
        name="Ghost",
        url_template="https://{username}.ghost.io",
        category="professional",
        not_found_indicators=("404",),
        found_indicators=("Subscribe", "Posts"),
        confidence_weight=0.70,
    ),
    "Hashnode": PlatformEntry(
        name="Hashnode",
        url_template="https://hashnode.com/@{username}",
        category="developer",
        not_found_indicators=("404", "Page not found"),
        found_indicators=("articles", "followers"),
        confidence_weight=0.85,
    ),
    # ── Streaming / Video ──────────────────────────────────────────────────────
    "Dailymotion": PlatformEntry(
        name="Dailymotion",
        url_template="https://www.dailymotion.com/{username}",
        category="creative",
        not_found_indicators=("This channel doesn't exist", "404"),
        found_indicators=("videos", "followers"),
        confidence_weight=0.82,
    ),
    "Rumble": PlatformEntry(
        name="Rumble",
        url_template="https://rumble.com/user/{username}",
        category="creative",
        not_found_indicators=("404", "not found"),
        found_indicators=("followers", "videos"),
        confidence_weight=0.78,
    ),
    "Odysee": PlatformEntry(
        name="Odysee",
        url_template="https://odysee.com/@{username}",
        category="creative",
        not_found_indicators=("Couldn't find", "404"),
        found_indicators=("followers", "videos"),
        confidence_weight=0.80,
    ),
    # ── Tech Communities ───────────────────────────────────────────────────────
    "Lobsters": PlatformEntry(
        name="Lobsters",
        url_template="https://lobste.rs/u/{username}",
        category="forum",
        not_found_indicators=("Unknown user", "404"),
        found_indicators=("karma", "stories submitted"),
        confidence_weight=0.92,
    ),
    "Fosstodon": PlatformEntry(
        name="Fosstodon",
        url_template="https://fosstodon.org/@{username}",
        category="developer",
        not_found_indicators=("The page you are looking for isn't here", "404"),
        found_indicators=("followers", "following"),
        confidence_weight=0.82,
    ),
    "SlashDot": PlatformEntry(
        name="SlashDot",
        url_template="https://slashdot.org/~{username}",
        category="forum",
        not_found_indicators=("User does not exist", "404"),
        found_indicators=("Friends", "Journal", "Karma"),
        confidence_weight=0.85,
    ),
    # ── Finance / Crypto ───────────────────────────────────────────────────────
    "Cashapp": PlatformEntry(
        name="Cashapp",
        url_template="https://cash.app/${username}",
        category="finance",
        not_found_indicators=("404", "not found"),
        found_indicators=("Pay", "$"),
        confidence_weight=0.75,
    ),
    "Venmo": PlatformEntry(
        name="Venmo",
        url_template="https://account.venmo.com/u/{username}",
        category="finance",
        not_found_indicators=("404", "not found"),
        found_indicators=("Pay", "Charge"),
        confidence_weight=0.75,
    ),
}

# Lookup helpers
CATEGORIES = frozenset(p.category for p in PLATFORM_REGISTRY.values())


def get_by_category(category: str) -> dict[str, PlatformEntry]:
    return {k: v for k, v in PLATFORM_REGISTRY.items() if v.category == category}


def all_platforms() -> dict[str, PlatformEntry]:
    return dict(PLATFORM_REGISTRY)
